# Generated by Django 4.1 on 2024-12-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_rename_horse_powers_car_horse_power"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="horse_power",
            new_name="horse_powers",
        ),
    ]
